import type { Metadata } from "next";
import localFont from "next/font/local";
import "../app/styles/globals.css";
import NavBar from "./_components/NavBar";
import Sky from "./_components/Sky";
import 'bootstrap/dist/css/bootstrap.min.css'
import { SkyProvider } from "./provider";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SkyProvider>
        
          <Sky>
              <div>
                <NavBar/>
              </div>
              <div>
                {children}
              </div>
          </Sky>
        
        </SkyProvider>
      </body>
    </html>
  );
}
